import { requiredNumber } from "./formValidation";

export const getMassCalculatorFields = ({
  shape,
  length,
  setLength,
  width,
  setWidth,
  outerDiameter,
  setOuterDiameter,
  innerDiameter,
  setInnerDiameter,
  totalLength,
  setTotalLength,
  thickness,
  setThickness,
  rodDiameter,
  setRodDiameter,
  rodLength,
  setRodLength,
  showRodShape,
}) => {
  const required = requiredNumber();

  return [
    {
      id: "length",
      label: "Długość boku A (mm):",
      value: length,
      onChange: (e) => setLength(e.target.value),
      placeholder: "Wpisz długość A w mm",
      showWhen: () => shape === "rectangle",
      validate: required,
    },
    {
      id: "width",
      label: "Długość boku B (mm):",
      value: width,
      onChange: (e) => setWidth(e.target.value),
      placeholder: "Wpisz długość B w mm",
      showWhen: () => shape === "rectangle",
      validate: required,
    },
    {
      id: "outerDiameter",
      label: "Średnica zewnętrzna (mm):",
      value: outerDiameter,
      onChange: (e) => setOuterDiameter(e.target.value),
      placeholder: "Wpisz średnicę zewnętrzną w mm",
      showWhen: () => shape === "circle" || shape === "semicircle",
      validate: required,
    },
    {
      id: "innerDiameter",
      label: "Średnica wewnętrzna (mm):",
      value: innerDiameter,
      onChange: (e) => setInnerDiameter(e.target.value),
      placeholder: "Wpisz średnicę wewnętrzną w mm (opcjonalnie)",
      showWhen: () => shape === "circle" || shape === "semicircle",
    },
    {
      id: "totalLength",
      label: "Całkowita długość boków (mm):",
      value: totalLength,
      onChange: (e) => setTotalLength(e.target.value),
      placeholder: "Wpisz całkowitą długość w mm",
      showWhen: () => shape === "totalLength",
      validate: required,
    },
    {
      id: "thickness",
      label: "Grubość materiału (mm):",
      value: thickness,
      onChange: (e) => setThickness(e.target.value),
      placeholder: "Wpisz grubość w mm",
      showWhen: () => shape !== "rod",
      validate: required,
    },
    {
      id: "rodDiameter",
      label: "Średnica pręta (mm):",
      value: rodDiameter,
      onChange: (e) => setRodDiameter(e.target.value),
      placeholder: "Wpisz średnicę pręta w mm",
      showWhen: () => shape === "rod" && showRodShape,
      validate: required,
    },
    {
      id: "rodLength",
      label: "Długość pręta (mm):",
      value: rodLength,
      onChange: (e) => setRodLength(e.target.value),
      placeholder: "Wpisz długość pręta w mm",
      showWhen: () => shape === "rod" && showRodShape,
      validate: required,
    },
  ];
};
